/turtlesim:
  ros__parameters:
    background_b: 10
    background_g: 16
    background_r: 255
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

/move_turtle:
  ros__parameters:
    vel: 1.0
    angle_vel: 3.0